default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: Conductor_dev

test:
  <<: *default
  database: Conductor_test

production:
  <<: *default
  database: Conductor_prod
